<?php

function oigus_seisukohad_form_alter(&$form, &$form_state, $form_id) {
  //$form['#action'] = str_replace('oiguskantsler.kalaruudus.ee', 'localhost', $form['#action']);
}


/**
 * Implements hook_menu().
 */
function oigus_seisukohad_menu() {
  $items = array();

  $items['seisukohad/arhiiv'] = array(
    'title' => 'Viimased seisukohad',
    'page callback' => 'oigus_seisukohad_arhiiv',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $items['seisukohad/otsing'] = array(
    'title' => 'Search results',
    'page callback' => 'oigus_seisukohad_otsing',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function oigus_seisukohad_search_lo() {
  return drupal_get_form('oigus_seisukohad_otsing_form');
}

function oigus_seisukohad_arhiiv($year = false, $month = false) {
  global $language;
  $output = '';

  drupal_set_title(t('Archive'));

  if(!$month && arg(2) == '12-kuud'){
    $current_year = format_date(time(), 'custom', 'Y');
    $current_month = format_date(time(), 'custom', 'm');

    $total = 0; $i = 0;
    while($i < 12){
      $y = $current_year;
      $m = $current_month-$i;
      if($m<=0){
        $m = $m+12;
        $y = $y-1;
      }
      $output .= oigus_seisukohad_arhiiv($y, $m);
      $i++;
    }

    return $output;
  }

  $year = (int) $year;
  $month = (int) $month;
  $months = array("January","February","March","April","May","June","July","August","September","October","November","December");

  $query = db_select('node', 'n')
    ->fields('n', array('nid', 'title', 'created'))
    ->condition('type', 'seisukoht')
    ->condition('language', $language->language)
    ->condition('status', 1)
    ->where('YEAR(FROM_UNIXTIME(created)) = :y AND MONTH(FROM_UNIXTIME(created)) = :m', array(':y' => $year, ':m' => $month))
    ->orderBy('created', 'DESC');

  $result = $query->execute();

  $output .= '<h3>'.t($months[$month-1]).' '.$year.'</h3>'.'<ul class="list02">';
  foreach ($result as $node){
    $output .= '<li><div class="indent clear"><p class="date">'.format_date($node->created, 'custom', 'd.m.Y').'</p>'.l($node->title, 'node/'.$node->nid).'</div></li>';
  }

  $output .= '</ul>';

  return $output;
}

function theme_oigus_seisukohad_kitsendused_form($variables) {
  $form = $variables['form'];

  $output = '<div class="filter clear" style="line-height: 14px;">';
  $output .= '<h3>' . t('Filter results') . '</h3>';
  $output .= '<div class="one-row">';

  $output .= '<div class="p"><label style="margin-left: 0 !important;">' . t('Years') . ':</label>';
  $output .= '<span class="select-wrap"><span class="select-inner">';
  $output .= drupal_render($form['aasta']);
  $output .= '</span></span></div>';

  $output .= '<label>' . t('Authorities') . ':</label>';
  $output .= '<span class="select-wrap"><span class="select-inner">';
  $output .= drupal_render($form['asutused']);
  $output .= '</span></span>';

  $output .= '</div>';
  $output .= '</div>';

  $output .= drupal_render_children($form);

  return $output;
}

function oigus_seisukohad_kitsendused_form($form, &$form_state) {
  $form = array();

  $form['sisutuup'] = array(
    '#type' => 'value',
    '#value' => 'seisukoht',
  );

  $query = oigus_detailotsing_build_query() + array('all' => TRUE);
  unset($query['aasta']);

  $seisukohad = oigus_detailotsing_tulemused($query);

  $form['aasta'] = array(
    '#title' => t('Years'),
    '#type' => 'select',
    '#options' => array(t('All years')) + drupal_map_assoc(array_keys($seisukohad)),
    '#default_value' => oigus_detailotsing_get_parameter_value('aasta'),
    '#id' => 'aasta',
    '#attributes' => array(
      'class' => array('input-select-medium'),
    ),
    '#title_display' => 'invisible',
  );

/*
  $alad = array();
  if(isset($_GET['valitsemisala'])) $alad = explode('-', check_plain($_GET['valitsemisala']));

  $catalog = taxonomy_vocabulary_machine_name_load(variable_get('oigus_seisukohad_valitsemisala', NULL));
  $tree = taxonomy_get_tree($catalog->vid, 0, 1, TRUE);
  $asutused = array(t('All authorities'));
  foreach ($tree as $term){
    $tree2 = taxonomy_get_tree($catalog->vid, $term->tid, 1, TRUE);
    foreach ($tree2 as $term2){
      foreach($term2->parents as $parent){
        if(count($alad) == 0 || in_array($parent, $alad)) $asutused[$term2->tid] = $term2->name;
      }
    }
  }


*/
//print_r(oigus_seisukohad_asutused_list());

  $query = oigus_detailotsing_build_query();
  unset($query['asutus']);

  $asutused = oigus_detailotsing_tulemused($query , 0, 0, 1);

  natsort($asutused);

  $form['asutused'] = array(
    '#title' => t('Authorities'),
    '#type' => 'select',
    '#options' => array(t('All authorities')) + $asutused,
    '#default_value' => oigus_detailotsing_get_parameter_value('asutus'),
    '#id' => 'asutused',
    '#attributes' => array(
      'class' => array('input-select-medium'),
    ),
    '#title_display' => 'invisible',
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Filter'),
    '#attributes' => array(
      'class' => array('element-invisible'),
    ),
  );

  return $form;
}

function oigus_seisukohad_kitsendused_form_submit($form, &$form_state) {
  //die(print_r($form_state['values']));
  if(isset($form_state['values']['asutused'])){
    $list = oigus_seisukohad_asutused_list($form_state['values']['aasta']);
    if(count($list) == 0){
      $form_state['values']['asutus'] = 0;
    }else{
      $form_state['values']['asutus'] = $form_state['values']['asutused'];
    }
    unset($form_state['values']['asutused']);
  }
  drupal_goto('seisukohad/otsing', array('query' => oigus_detailotsing_build_query(array_map('trim', $form_state['values']))));
}

function oigus_seisukohad_theme() {
  return array(
    'oigus_seisukohad_otsing_form' => array(
      'render element' => 'form',
    ),
    'oigus_seisukohad_kitsendused_form' => array(
      'render element' => 'form',
    ),
    'oigus_seisukohad_uldotsing_form' => array(
      'render element' => 'form',
    ),
  );
}

function theme_oigus_seisukohad_otsing_form($variables) {
  global $_domain;
  $form = $variables['form'];
  
  $ml = false;
  if(isset($_GET['menetluse_liik'])) $ml = $_GET['menetluse_liik'];


  $output = '<div class="views-exposed-form">';
  

  $output .= '<div class="form-group">';
  $output .= ' <label for="tagword">' . t('Keyword') . ':</label>';
  $output .= '<span class="input-wrap">';
  $output .= '<span class="input-inner">';
  $output .= drupal_render($form['marksonad']);
  $output .= '</span>';
  $output .= '</span>';
  $output .= '</div>';

  



  $output .= '<div class="form-row clear">';
  

  $output .= '<div class="row">';
  $output .= '<div class="form-group col-lg-6">';
  $output .= '<label for="datefrom">' . t('From') . ':</label>';
  $output .= drupal_render($form['alates']);
  $output .= '</div>';
  
                                          
  $output .= '<div class="form-row"></div>';
  $output .= '<div class="col2">';

  $output .= '<div class="form-group col-lg-6">';
  $output .= ' <label for="dateto">' . t('To') . ':</label>';
  $output .= '<span class="input-wrap">';
  $output .= '<span class="input-inner">';
  $output .= drupal_render($form['kuni']);
  $output .= '</span>';
  $output .= '</span>';
  $output .= '</div>';

  $output .= '</div>';
  $output .= '</div>';

  $output .= '<div class="form-row">';
  $output .= '<label for="menetluse_liik">' . t('Type of proceeding') . ':</label>';
  $output .= '<span class="select-wrap">';
  $output .= '<span class="select-inner">';
  $output .= drupal_render($form['menetluse_liik']);
  $output .= '</span>';
  $output .= '</span>';
  $output .= '</div>';

  $output .= '<div id="ml1" class="form-row"'.($ml != 3 ? ' style="display:none;"' : '').'>';
  $output .= '<label for="dokumendi_liik">' . t('Type of document') . ':</label>';
  $output .= '<span class="select-wrap">';
  $output .= '<span class="select-inner">';
  $output .= drupal_render($form['dokumendi_liik']);
  $output .= '</span>';
  $output .= '</span>';
  $output .= '</div>';

  $output .= '<div id="ml2" class="form-row"'.($ml != 4 ? ' style="display:none;"' : '').'>';
  $output .= '<label for="dokumendi_liik2">' . t('Type of document') . ':</label>';
  $output .= '<span class="select-wrap">';
  $output .= '<span class="select-inner">';
  $output .= drupal_render($form['dokumendi_liik2']);
  $output .= '</span>';
  $output .= '</span>';
  $output .= '</div>';

  $output .= '<div id="ml3" class="form-row"'.($ml != 5 ? ' style="display:none;"' : '').'>';
  $output .= '<label for="dokumendi_liik3">' . t('Type of document') . ':</label>';
  $output .= '<span class="select-wrap">';
  $output .= '<span class="select-inner">';
  $output .= drupal_render($form['dokumendi_liik3']);
  $output .= '</span>';
  $output .= '</span>';
  $output .= '</div>';

  $output .= '<div class="form-row">';
  $output .= '<label for="valitsemisala">' . t('Area of government') . ':</label>';
  $output .= '<span class="select-wrap">';
  $output .= '<span class="select-inner">';
  $output .= drupal_render($form['valitsemisala']);
  $output .= '</span>';
  $output .= '</span>';
  $output .= '</div>';

  $output .= '<div class="form-row">';
  $output .= '<label for="asutus">' . t('Authority') . ':</label>';
  $output .= '<span class="select-wrap">';
  $output .= '<span class="select-inner">';
  $output .= drupal_render($form['asutus']);
  $output .= '</span>';
  $output .= '</span>';
  $output .= '</div>';

 


  $output .= '<div class="action clear">';
  $output .= '<button class="btn-default btn" type="submit"><span><strong>'.t('Search').'</strong></span></button>';
  
  $output .= '</div>';


  $output .= drupal_render_children($form);

  $output .= '</div>';
  $output .= '</div>';
  
  

  return $output;
}

function oigus_seisukohad_otsing_form() {
  global $_domain;
  
  $strings=explode('/',$_GET['q']);
  
  if(isset($strings[1])){
    if($strings[1]=='oiguskaitse'){
      $lahter=4;
    }
    elseif($strings[1]=='jarelvalve'){
      $lahter=3;
    }
  }
  $form = array();

  $form['sisutuup'] = array(
    '#type' => 'value',
    '#value' => 'seisukoht',
  );

  $form['vaade'] = array(
    '#type' => 'value',
    '#value' => 'otsing',
  );

  $form['marksonad'] = array(
    '#type' => 'textfield',
    '#title' => t('Keyword'),
    '#default_value' => oigus_detailotsing_get_parameter_value('marksonad'),
    '#id' => 'marksonad',
    '#attributes' => array(
      'class' => array(
        
        0=> 'text',
        
        1=>'fullwith',
        ),
    ),
    '#title_display' => 'invisible',
  );

  $form['alates'] = array(
    '#date_label_position' => 'hidden',
    '#type' => 'date_popup',
    '#title' => t('From'),
    '#default_value' => oigus_detailotsing_get_parameter_value('alates'),
    '#id' => '',
    '#date_format' => 'd.m.Y',
    '#attributes' => array(
      'class' => array('date'),
    ),
    '#title_display' => 'invisible',
  );

  $form['kuni'] = array(
    '#date_label_position' => 'hidden',
    '#type' => 'date_popup',
    '#title' => t('To'),
    '#default_value' => oigus_detailotsing_get_parameter_value('kuni'),
    '#id' => 'kuni',
    '#date_format' => 'd.m.Y',
    
    '#attributes' => array(
      'class' => array('date'),
    ),
    '#title_display' => 'invisible',
  );
  
  $form['menetluse_liik'] = array(
    '#type' => 'select',
    '#title' => t('Type of proceeding'),
    '#options' => array(t('All')) + oigus_seisukohad_menetluse_liigid(),
    '#default_value' => oigus_detailotsing_get_parameter_value('menetluse_liik'),
    '#id' => 'menetluse_liik',
    '#attributes' => array(
      'class' => array(0 => 'input-select-medium',1=>'fullwith'),
    ),
    '#title_display' => 'invisible',
  );
  
  if(isset($lahter) and !empty($lahter)){
    $form['menetluse_liik']['#default_value']=$lahter;
  }

  $form['dokumendi_liik'] = array(
    '#type' => 'select',
    '#title' => t('Type of document'),
    '#options' => array(t('All')) + oigus_seisukohad_dokumendi_liigid(),
    '#default_value' => oigus_detailotsing_get_parameter_value('dokumendi_liik'),
    '#id' => 'dokumendi_liik',
    '#attributes' => array(
      'class' => array(0 => 'input-select-medium',1=>'fullwith'),
    ),
    '#title_display' => 'invisible',
  );

  $form['dokumendi_liik2'] = array(
    '#type' => 'select',
    '#title' => t('Type of document'),
    '#options' => array(t('All')) + oigus_seisukohad_dokumendi_liigid2(),
    '#default_value' => oigus_detailotsing_get_parameter_value('dokumendi_liik2'),
    '#id' => 'dokumendi_liik2',
    '#attributes' => array(
      'class' => array(0 => 'input-select-medium',1=>'fullwith'),
    ),
    '#title_display' => 'invisible',
  );

  $form['dokumendi_liik3'] = array(
    '#type' => 'select',
    '#title' => t('Type of document'),
    '#options' => array(t('All')) + oigus_seisukohad_dokumendi_liigid3(),
    '#default_value' => oigus_detailotsing_get_parameter_value('dokumendi_liik3'),
    '#id' => 'dokumendi_liik3',
    '#attributes' => array(
      'class' => array(0 => 'input-select-medium',1=>'fullwith'),
    ),
    '#title_display' => 'invisible',
  );

  $form['valitsemisala'] = array(
    '#type' => 'select',
    '#title' => t('Area of government'),
    '#options' => array(t('All')) + oigus_seisukohad_valitsemisalad(),
    '#default_value' => oigus_detailotsing_get_parameter_value('valitsemisala'),
    '#id' => 'valitsemisala',
    '#attributes' => array(
      'class' => array(0 => 'input-select-medium',1=>'fullwith'),
    ),
    '#title_display' => 'invisible',
  );
  
  $form['dokumendist'] = array(
    '#type' => 'checkbox',
    '#title' => t('Search for a keyword also within a full-text document'),
    '#default_value' => oigus_detailotsing_get_parameter_value('dokumendist'),
  );
  $form['asutus'] = array(
    '#type' => 'select',
    '#title' => t('Authority'),
    '#options' => array(t('All')) + oigus_seisukohad_asutused(),
    '#default_value' => oigus_detailotsing_get_parameter_value('asutus'),
    '#id' => 'asutus',
    '#attributes' => array(
      'class' => array(0 => 'input-select-medium',1=>'fullwith'),
    ),
    '#title_display' => 'invisible',
  );

  $form['submit'] = array(
    '#attributes'=> array(
      
      'class'=>array(
        
        0=>'btn-default',
        
        1=>'btn',
        ),
      ),
    '#type' => 'submit',
    
    '#value' => t('Search'),
    '#title_display' => 'invisible',
  );
  if($_domain['domain_id'] == 0) $form['submit']['#attributes'] = array('class' => array('element-invisible'));


  $catalog = taxonomy_vocabulary_machine_name_load(variable_get('oigus_seisukohad_valitsemisala', NULL));
  $tree = taxonomy_get_tree($catalog->vid, 0, 1, TRUE);
  $asutused = array();
  foreach ($tree as $term){
    $asutused2 = array();
    $tree2 = taxonomy_get_tree($catalog->vid, $term->tid, 1, TRUE);
    foreach ($tree2 as $term2){
      $asutused2[$term2->tid] = $term2->tid;
    }
    $asutused[$term->tid] = $asutused2;
  }

  /*drupal_add_js("

    (function($) {
    	$(document).ready(function() {
        var asutused = ".drupal_json_encode($asutused).";
        function fnc() {
          var v = $('#valitsemisala').val();
          if(v == 0){
            $('#asutus_list li').show();
          }else{
            var list = asutused[v];
            $('#asutus_list li').hide();
            $('#asutus_list li[rel=0]').show();
            for(var i in list){
              $('#asutus_list li[rel='+i+']').show();
            }
          }
        }
        $('#valitsemisala_list li.current').live('click', function(){ fnc(); $('#asutus').linkselect('val', 0); });
        setTimeout(fnc, 500);
      });
    })(jQuery);", array('type' => 'inline', 'scope' => 'footer', 'weight' => 25));*/

  return $form;
}

function oigus_seisukohad_otsing_form_submit($form, &$form_state) {
  
  if($form_state['values']['menetluse_liik'] == 3){
    $form_state['values']['dokumendi_liik2'] = 0;
    $form_state['values']['dokumendi_liik3'] = 0;
  }
  if($form_state['values']['menetluse_liik'] == 4){
    $form_state['values']['dokumendi_liik'] = 0;
    $form_state['values']['dokumendi_liik3'] = 0;
  }
  if($form_state['values']['menetluse_liik'] == 5){
    $form_state['values']['dokumendi_liik'] = 0;
    $form_state['values']['dokumendi_liik2'] = 0;
  }
  drupal_goto('seisukohad/otsing', array('query' => oigus_detailotsing_build_query(array_map('trim', $form_state['values']))));
}

function theme_oigus_seisukohad_uldotsing_form($variables) {
  $form = $variables['form'];

  $output = '';

  $output .= '<div class="views-exposed-form">';
  $output .= '<div class="views-exposed-widgets clearfix">';
  $output .= '<div id="edit-otsisna-wrapper" class="views-exposed-widget views-widget-filter-search_api_views_fulltext">';
  $output .= '<div class="views-widget">';
  $output .= '<div class="form-item form-type-textfield form-item-otsisõna">';
  $output .= drupal_render($form['marksonad']);
  $output .= '</div>';
  $output .= '</div>';
  $output .= '</div>';
  $output .= '<div class="views-exposed-widget views-submit-button">';
  $output .= drupal_render($form['submit']);
  $output .= '</div>';
  $output .= '</div>';
  $output .= '</div>';

  $output .= drupal_render_children($form);

  return $output;
}

function oigus_seisukohad_uldotsing_form() {
  $form = array();

  $form['#id'] = 'views-exposed-form-seisukohtade-otsing-page';

  $form['sisutuup'] = array(
    '#type' => 'value',
    '#value' => 'seisukoht',
  );

  $form['dokumendist'] = array(
    '#type' => 'value',
    '#value' => 1,
  );

  $form['vaade'] = array(
    '#type' => 'value',
    '#value' => 'otsing',
  );

  $form['marksonad'] = array(
    '#type' => 'textfield',
    '#title' => t('Märksõna'),
    '#default_value' => oigus_detailotsing_get_parameter_value('marksonad'),
    '#default_value' => t('Search opinions'),
    '#id' => 'edit-otsisna',
    '#attributes' => array(
      'class' => array('text'),
    ),
    '#title_display' => 'invisible',
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Otsi'),
    '#id' => 'edit-submit-seisukohtade-otsing',
  );

  return $form;
}

function oigus_seisukohad_uldotsing_form_submit($form, &$form_state) {
  drupal_goto('seisukohad/otsing', array('query' => oigus_detailotsing_build_query(array_map('trim', $form_state['values']))));
}

function oigus_seisukohad_otsing() {
  global $_domain;
  global $language;
  $output = '';

  drupal_set_title(t('Search', array(), array('context' => 'page title')));

  if($_domain['domain_id'] == 2){
    $output .= render(drupal_get_form('oigus_seisukohad_otsing_form'));
  }

  if(isset($_GET['vaade'])){
    $count = oigus_detailotsing_tulemused(oigus_detailotsing_build_query(), 0, 1);
    $seisukohad = oigus_detailotsing_tulemused(oigus_detailotsing_build_query(), 1);
    //$count = count($seisukohad);
    drupal_set_title(t('Search results').' ('.$count.')');
    //$seisukohad = oigus_detailotsing_tulemused(oigus_detailotsing_build_query(), 0);

    $all = (int) $_GET['all'];

    $limit = 10;
    $pages = ceil($count/$limit);
    $page = (int) $_GET['page'];
    if(!$page || $page>$pages) $page = 0;

    if($all != 1){
      $start = 1;
      if($page>0) $start = $page*$limit+1;
      $end = ($start+$limit-1);
      if($end>$count) $end = $count;
      //$seisukohad = array_chunk($seisukohad, $limit);
      //$seisukohad = $seisukohad[$page-1];
    }else{
      $start = 1;
      $end = $count;
    }
    
    $output .= ' <table class="table">';
    foreach ($seisukohad as $node) {
      
      $tax_load=taxonomy_term_load($node->field_tags['und'][0]['tid']);
      
      $output .= ' <tr>
                                <td><span class="date">' . format_date($node->created, 'custom', 'd.m.Y') . '</span></td><td>' . l($node->title, 'node/' . $node->nid) . '<p class="small">'.$node->body[$language->language][0]['value'].'</p></td></row>';
    }
    $output .= '</table>';

		$int = $start.'-'.$end;
		if($count == 0){
		  $int = 0;
		  $output .= '<p>'.t('Your search yielded no results').'</p>';
		}

    $query = pager_get_query_parameters();

/*
    $output .= '<div class="pager clear">';

    if($all != 1){
      $output .= '<ul>';
      if(($page-1)>0){
        $query['pager'] = ($page-1);
        $output .= '<li class="prev"><a href="'.url('seisukohad/otsing', array('query' => $query)).'">'.t('Eelmine').'</a></li>';
      }else{
        $output .= '<li class="prev"><span>'.t('Eelmine').'</span></li>';
      }

  		$i = 0;
  		while($i < $pages){
  		  $query['pager'] = ($i+1);
  		  $output .= '<li'.($i == $page ? ' class="active"' : '').'><a href="'.url('seisukohad/otsing', array('query' => $query)).'">'.($i+1).'</a></li>';
  		  $i++;
  		}

      if(($page+1)<=$pages){
        $query['pager'] = ($page+1);
        $output .= '<li class="next"><a href="'.url('seisukohad/otsing', array('query' => $query)).'">'.t('Järgmine').'</a></li>';
      }else{
        $output .= '<li class="next"><span>'.t('Järgmine').'</span></li>';
      }
  		$output .= '</ul>';
		}
*/

		$output .= theme('pager');

		$output .= '<p id="pager2">'.t('Showing').': '.$int.' <span>|</span> '.t('Total').': '.$count;
		if($count>$limit){
  		if($all != 1){
    		unset($query['page']);
    		$query['all'] = 1;
    		$output .= ' <span>|</span> <a href="'.url('seisukohad/otsing', array('query' => $query)).'">'.t('Show all').'</a>';

  		}else{
    		unset($query['page']);
    		unset($query['all']);
    		$output .= ' <span>|</span> <a href="'.url('seisukohad/otsing', array('query' => $query)).'">'.t('Use pager').'</a>';
  		}
		}
    $output .= '</p></div>';



  }elseif($_domain['domain_id'] == 0){
/*
    $list = oigus_seisukohad_asutused_list();
    if($_GET['asutus']>0 && count($list) == 0){

    }
*/

    $seisukohad = oigus_detailotsing_tulemused(oigus_detailotsing_build_query());
/*
    if (isset($_GET['dokumendi_liik']) && isset($_GET['valitsemisala'])) {
      $title1 = array_values(oigus_seisukohad_get_dokumendi_liik($_GET['dokumendi_liik']));
      $title2 = array_values(oigus_seisukohad_get_valitsemisala($_GET['valitsemisala']));
      if(isset($title1[0]) && isset($title2[0])) drupal_set_title($title1[0] . ' | ' . $title2[0]);
    }
*/
    drupal_set_title(t('Opinions'));

    $query = oigus_detailotsing_build_query() + array('all' => TRUE);
    unset($query['aasta']);

    $tulemused = array_values(oigus_detailotsing_tulemused($query));

    $total = 0;

    foreach ($tulemused as $tulemus) {
      foreach ($tulemus as $item) {
        $total++;
      }
    }

    $all = (int) $_GET['all'];

    $limit = 10;
    $pages = ceil($total/$limit);
    $page = (int) $_GET['page'];
    if(!$page || $page>$pages) $page = 0;

    if($all != 1){
      $start = 1;
      if($page>0) $start = $page*$limit+1;
      $end = ($start+$limit-1);
      if($end>$total) $end = $total;
      //$seisukohad = array_chunk($seisukohad, $limit);
      //$seisukohad = $seisukohad[$page-1];
    }else{
      $start = 1;
      $end = $total;
    }

		$int = $start.'-'.$end;

		if($total == 0){
		  $int = 0;
		}

    $output = render(drupal_get_form('oigus_seisukohad_kitsendused_form'));

    if(count($seisukohad) > 0){
      $count = 0;

      foreach ($seisukohad as $aasta => $nodes) {
        $output .= '<h3>' . $aasta . '</h3><ul class="list02">';

        foreach ($nodes as $node) {
          $count++;

          $output .= '<li><div class="indent clear"><p class="date">' . format_date($node->created, 'custom', 'd.m.Y') . '</p>' . l($node->title, 'node/' . $node->nid) . '</div></li>';
        }

        $output .= '</ul>';
      }

      if (!$all && !isset($_GET['aasta'])) {
        pager_default_initialize($total, 10);

        $output .= theme('pager');
      }

      if (($count < $total || $all) && !isset($_GET['aasta'])) {
        $output .= '<p id="pager2">'.t('Showing').': '.$int.' <span>|</span> '.t('Total').': '.$total;

        $query = pager_get_query_parameters();

        if($total>$limit){
          if($all != 1){
            unset($query['page']);
            $query['all'] = 1;
            $output .= ' <span>|</span> <a href="'.url('seisukohad/otsing', array('query' => $query)).'">'.t('Show all').'</a>';

          }else{
            unset($query['page']);
            unset($query['all']);
            $output .= ' <span>|</span> <a href="'.url('seisukohad/otsing', array('query' => $query)).'">'.t('Use pager').'</a>';
          }
        }
        $output .= '</p>';
      }
    }
    else{
      $output .= '<p>'.t('These conditions yielded no opinions to show').'</p>';
    }
  }

  return $output;
}

/**
 * Implements hook_block_info().
 *
 * This hook declares what blocks are provided by the module.
 */
function oigus_seisukohad_block_info() {
  $blocks = array();

  $blocks['oigus_seisukohad_uldotsing'] = array(
    'info' => t('Seisukohad: Üldotsing'),
    'weight' => -10,
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'status' => TRUE,
  );

  $blocks['oigus_seisukohad_otsinguvorm'] = array(
    'info' => t('Seisukohad: Otsi'),
    'weight' => -10,
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'status' => TRUE,
  );

  $blocks['oigus_seisukohad_kuud'] = array(
    'info' => t('Seisukohad: Viimase 12 kuu seisukohad'),
    'region' => 'sidebar_first',
    'weight' => -9,
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'seisukohad/viimased-seisukohad',
    'status' => TRUE,
  );

  $blocks['oigus_seisukohad_liigid'] = array(
    'info' => t('Seisukohad: Liigi põhiselt'),
    'weight' => -10,
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'status' => TRUE,
  );

  $blocks['oigus_seisukohad_alad'] = array(
    'info' => t('Seisukohad: Valitsemisala põhiselt'),
    'weight' => -9,
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'status' => TRUE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 *
 * This hook generates the contents of the blocks themselves.
 */
function oigus_seisukohad_block_view($delta = '') {
  switch ($delta) {
    case 'oigus_seisukohad_uldotsing':
      $block['subject'] = '<none>';
      $block['content'] = drupal_get_form('oigus_seisukohad_uldotsing_form');

      break;
    case 'oigus_seisukohad_otsinguvorm':
      $block['subject'] = '<none>';
      $block['content'] = drupal_get_form('oigus_seisukohad_otsing_form');

      break;
    case 'oigus_seisukohad_kuud':
      $block['subject'] = t('Opinions of the last 12 months');
      $block['content'] = array('#markup' => '<div class="sidepanel">
                        <h2 class="title">'.t('Opinions of the last 12 months').'</h2>'.oigus_seisukohad_kuud().'</div>');

      break;
    case 'oigus_seisukohad_liigid':
      $block['subject'] = t('Type of opinion');

      if (isset($_GET['vaade'])) {
        return $block;;
      }

      $output = '<ul class="list03 category-select">';


      if((arg(0) == 'node' && (arg(1) == 1435 || arg(1) == 1551 || arg(1) == 1558)) || $_GET['menetluse_liik'] == 4){
        $dokumendi_liigid = oigus_seisukohad_dokumendi_liigid2();
        $dl = 'dokumendi_liik2';
      }else if((arg(0) == 'node' && (arg(1) == 1436 || arg(1) == 1552 || arg(1) == 1559)) || $_GET['menetluse_liik'] == 5){
        $dokumendi_liigid = oigus_seisukohad_dokumendi_liigid3();
        $dl = 'dokumendi_liik3';
      }else{
        $dokumendi_liigid = oigus_seisukohad_dokumendi_liigid();
        $dl = 'dokumendi_liik';
      }

      $valitsemisala = array_keys(oigus_seisukohad_get_valitsemisala(oigus_detailotsing_get_parameter_value('valitsemisala')));

      foreach ($dokumendi_liigid as $tid => $dokumendi_liik) {
        $query = array(
          //'dokumendi_liik' => $tid,
          'sisutuup' => 'seisukoht',
        );

        if (isset($_GET['menetluse_liik'])) {
          $query['menetluse_liik'] = check_plain($_GET['menetluse_liik']);
        }
        if(arg(0) == 'node' && (arg(1) == 25 || arg(1) == 1560 || arg(1) == 1557)) $query['menetluse_liik'] = 3;
        if(arg(0) == 'node' && (arg(1) == 1435 || arg(1) == 1551 || arg(1) == 1558)) $query['menetluse_liik'] = 4;
        if(arg(0) == 'node' && (arg(1) == 1436 || arg(1) == 1552 || arg(1) == 1559)) $query['menetluse_liik'] = 5;

        if (isset($_GET['valitsemisala'])) {
          $query['valitsemisala'] = $valitsemisala[0];
        }
        if (isset($_GET[$dl])) {
          $liigid = explode('-', check_plain($_GET[$dl]));
          if (in_array($tid, $liigid)){
            $key = array_search($tid, $liigid);
            unset($liigid[$key]);
          }else{
            $liigid[] = $tid;
          }
        }else{
          $liigid = array($tid);
        }
        if(count($liigid)) $query[$dl] = implode('-', $liigid);

        $output .= '<li' . (!in_array($tid, $liigid) ? ' class="active"' : '') . '><a href="' . url('seisukohad/otsing', array('query' => $query)) . '">' . $dokumendi_liik . '</a></li>';
      }

      $output .= '</ul>';

      $block['content'] = array('#markup' => $output);

      break;
    case 'oigus_seisukohad_alad':
      $block['subject'] = t('Area of government ');

      if (isset($_GET['vaade']) || $_GET['menetluse_liik'] == 5) {
        return $block;
      }

      $output = '<ul class="list03 category-select">';

      $valitsemisalad = oigus_seisukohad_valitsemisalad();

      if((arg(0) == 'node' && (arg(1) == 1435 || arg(1) == 1551 || arg(1) == 1558)) || $_GET['menetluse_liik'] == 4){
        $dl = 'dokumendi_liik2';
      }else if((arg(0) == 'node' && (arg(1) == 1436 || arg(1) == 1552 || arg(1) == 1559)) || $_GET['menetluse_liik'] == 5){
        $dl = 'dokumendi_liik3';
      }else{
        $dl = 'dokumendi_liik';
      }

      $dokumendi_liik = array_keys(oigus_seisukohad_get_dokumendi_liik(oigus_detailotsing_get_parameter_value($dl), $dl));

      foreach ($valitsemisalad as $tid => $valitsemisala) {
        $query = array(
          //'valitsemisala' => $tid,
          'sisutuup' => 'seisukoht',
        );

        if (isset($_GET['menetluse_liik'])) {
          $query['menetluse_liik'] = check_plain($_GET['menetluse_liik']);
        }
        if(arg(0) == 'node' && (arg(1) == 25 || arg(1) == 1560 || arg(1) == 1557)) $query['menetluse_liik'] = 3;
        if(arg(0) == 'node' && (arg(1) == 1435 || arg(1) == 1551 || arg(1) == 1558)) $query['menetluse_liik'] = 4;
        if(arg(0) == 'node' && (arg(1) == 1436 || arg(1) == 1552 || arg(1) == 1559)) $query['menetluse_liik'] = 5;

        if (isset($_GET[$dl])) {
          $query[$dl] = $dokumendi_liik[0];
        }
        if (isset($_GET['valitsemisala'])) {
          $alad = explode('-', check_plain($_GET['valitsemisala']));
          if (in_array($tid, $alad)){
            $key = array_search($tid, $alad);
            unset($alad[$key]);
          }else{
            $alad[] = $tid;
          }
        }else{
          $alad = array($tid);
        }
        if(count($alad)) $query['valitsemisala'] = implode('-', $alad);

        $output .= '<li' . (!in_array($tid, $alad) ? ' class="active"' : '') . '><a href="' . url('seisukohad/otsing', array('query' => $query)) . '">' . $valitsemisala . '</a></li>';
      }

      $output .= '</ul>';

      $block['content'] = array('#markup' => $output);

      break;
  }

  return $block;
}

function oigus_seisukohad_get_dokumendi_liik($tid = NULL, $dl = false) {
  $liigid = oigus_seisukohad_dokumendi_liigid();
  if($dl == 'dokumendi_liik2') $liigid = oigus_seisukohad_dokumendi_liigid2();
  if($dl == 'dokumendi_liik3') $liigid = oigus_seisukohad_dokumendi_liigid3();

  if (!$liigid) {
    return;
  }

  //if (!oigus_seisukohad_dokumendi_liik_exists($tid)) {
  if (!in_array($tid, array_keys($liigid))) {
    $tid = array_shift(array_keys($liigid));
  }

  return array($tid => $liigid[$tid]);;
}

function oigus_seisukohad_get_valitsemisala($tid = NULL) {
  $valitsemisalad = oigus_seisukohad_valitsemisalad();

  if (!$valitsemisalad) {
    return;
  }

  if (!oigus_seisukohad_valitsemisala_exists($tid)) {
    $tid = array_shift(array_keys($valitsemisalad));
  }

  return array($tid => $valitsemisalad[$tid]);
}

function oigus_seisukohad_valitsemisala_exists($tid) {
  return in_array($tid, array_keys(oigus_seisukohad_valitsemisalad()));
}

function oigus_seisukohad_dokumendi_liik_exists($tid) {
  return in_array($tid, array_keys(oigus_seisukohad_dokumendi_liigid()));
}

function oigus_seisukohad_valitsemisalad() {
  $valitsemisalad = array();

  $catalog = taxonomy_vocabulary_machine_name_load('valitsemisala');
  $tree = taxonomy_get_tree($catalog->vid, 0, 1, TRUE);

  foreach ($tree as $term){
    $valitsemisalad[$term->tid] = function_exists('i18n_string') ? i18n_string('taxonomy:term:'.$term->tid.':name', $term->name) : $term->name;
  }

  return $valitsemisalad;
}

function oigus_seisukohad_dokumendi_liigid() {
  $dokumendi_liigid = array();

  $catalog = taxonomy_vocabulary_machine_name_load('');
  $tree = taxonomy_get_tree($catalog->vid, 0, NULL, TRUE);

  //die(print_r($tree));

  foreach ($tree as $term){
    $dokumendi_liigid[$term->tid] = function_exists('i18n_string') ? i18n_string('taxonomy:term:'.$term->tid.':name', $term->name) : $term->name;
  }

  return $dokumendi_liigid;
}
function oigus_seisukohad_dokumendi_liigid2() {
  $dokumendi_liigid = array();

  $catalog = taxonomy_vocabulary_machine_name_load(variable_get('oigus_seisukohad_dokumendi_liik_pohioigused', 'dokumendi_liik_pohioigused'));
  $tree = taxonomy_get_tree($catalog->vid, 0, NULL, TRUE);

  foreach ($tree as $term){
    $dokumendi_liigid[$term->tid] = function_exists('i18n_string') ? i18n_string('taxonomy:term:'.$term->tid.':name', $term->name) : $term->name;
  }

  return $dokumendi_liigid;
}
function oigus_seisukohad_dokumendi_liigid3() {
  $dokumendi_liigid = array();

  $catalog = taxonomy_vocabulary_machine_name_load(variable_get('oigus_seisukohad_dokumendi_liik_muud', 'dokumendi_liik_muud_lesanded_'));
  $tree = taxonomy_get_tree($catalog->vid, 0, NULL, TRUE);

  foreach ($tree as $term){
    $dokumendi_liigid[$term->tid] = function_exists('i18n_string') ? i18n_string('taxonomy:term:'.$term->tid.':name', $term->name) : $term->name;
  }

  return $dokumendi_liigid;
}

function oigus_seisukohad_menetluse_liigid() {
  $menetluse_liigid = array();

  $catalog = taxonomy_vocabulary_machine_name_load('menetluse_liik');
  
  
  $tree = taxonomy_get_tree($catalog->vid, 0, NULL, TRUE);

  foreach ($tree as $term){
    $menetluse_liigid[$term->tid] = function_exists('i18n_string') ? i18n_string('taxonomy:term:'.$term->tid.':name', $term->name) : $term->name;
  }

  return $menetluse_liigid;
}

function oigus_seisukohad_asutused() {
  $asutused = array();

  $catalog = taxonomy_vocabulary_machine_name_load('valitsemisala');
  $tree = taxonomy_get_tree($catalog->vid, 0, NULL, TRUE);

  foreach ($tree as $term){
    if($term->depth>0) $asutused[$term->tid] = function_exists('i18n_string') ? i18n_string('taxonomy:term:'.$term->tid.':name', $term->name) : $term->name;
  }

  return $asutused;
}

function oigus_seisukohad_sildid() {
  $sildid = array();

  $catalog = taxonomy_vocabulary_machine_name_load(variable_get('oigus_seisukohad_sildid', NULL));
  $tree = taxonomy_get_tree($catalog->vid, 0, NULL, TRUE);

  foreach ($tree as $term){
    $sildid[$term->tid] = function_exists('i18n_string') ? i18n_string('taxonomy:term:'.$term->tid.':name', $term->name) : $term->name;
  }

  return $sildid;
}

function oigus_seisukohad_aastad() {
  $parameters = array();

  $parameters['sisutuup'] = 'seisukoht';
  $parameters['dokumendi_liik'] = oigus_detailotsing_get_parameter_value('dokumendi_liik');
  $parameters['valitsemisala'] = oigus_detailotsing_get_parameter_value('valitsemisala');

  return drupal_map_assoc(array_keys(oigus_detailotsing_tulemused($parameters)));
}

function oigus_seisukohad_asutused_list($year = false) {
  $parameters = array();

  $parameters['sisutuup'] = 'seisukoht';
  $parameters['dokumendi_liik'] = oigus_detailotsing_get_parameter_value('dokumendi_liik');
  $parameters['valitsemisala'] = oigus_detailotsing_get_parameter_value('valitsemisala');
  if($year){
     $parameters['year'] = $year;
  }else{
     $parameters['year'] = oigus_detailotsing_get_parameter_value('aasta');
  }

  return oigus_detailotsing_tulemused($parameters, 0, 0, 1);
}

function oigus_seisukohad_kuud_count($y, $m) {
  global $language;
  $result = db_query("SELECT COUNT(*) as count FROM {node} WHERE type = 'seisukoht' AND status = 1 AND language = :lang AND YEAR(FROM_UNIXTIME(created)) = :y AND MONTH(FROM_UNIXTIME(created)) = :m", array(':lang' => $language->language,':y' => $y, ':m' => $m))->fetchField();
  return $result;
}

function oigus_seisukohad_kuud() {
  $output = '';

  $months = array("January","February","March","April","May","June","July","August","September","October","November","December");
  $current_year = format_date(time(), 'custom', 'Y');
  $current_month = format_date(time(), 'custom', 'm');

  $total = 0; $i = 0;
  while($i < 12){
    $y = $current_year;
    $m = $current_month-$i;
    if($m<=0){
      $m = $m+12;
      $y = $y-1;
    }
    $c = oigus_seisukohad_kuud_count($y, $m);
    if($c == 0) {
/*
      if ($m == $current_month) {
        $output .= '<li><a class="list03hover" href="">'.t($months[$m-1]).' <span>('.$c.')</span></a></li>';
      }
      else {
*/
        $output .= '<li class="list-group-item">'.t($months[$m-1]).' <span>('.$c.')</span></li>';
      //}
    }else{
       
      $output .= '<a class="list-group-item"  href="'.url('seisukohad/arhiiv/'.$y.'/'.$m).'"><span class="badge">'.$c.'12</span>'.t($months[$m-1]).'</a>';
    }
    $total = $total + $c;
    $i++;
  }
  
	$output .= '<a  class="list-group-item" href="'.url('seisukohad/arhiiv/12-kuud').'">'.t('All last 12 months').' <span>('.$total.')</span></a>';

  return $output;
}
